title: Project 2025 Assistant
email: ConcernedCitizen2025AD@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Explore detailed analyses and summaries of "Mandate for Leadership: The Conservative Promise".
baseurl: "/project-2025-assistant" # the subpath of your site
url: "https://concernedcitizen2025.github.io" # the base hostname & protocol for your site
logo: /assets/images/logo.jpg

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
