title: Project 2025 Assistant
email: ConcernedCitizen2025AD@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Explore detailed analyses and summaries of "Mandate for Leadership: The Conservative Promise".
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://<your-username>.github.io/project-2025-assistant" # the base hostname & protocol for your site

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
